name: My First GitHub Actions

on: [push]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      run: |
        cd code
        python -m pytest addition.py
    - name: SonarQube Analysis
      run: |
        mvn sonar:sonar \
          -Dsonar.host.url=http://54.208.229.184:9000 \
          -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: ./dist/*.tar.gz
