name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted  # Using your self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Build Python package
        run: |
          python setup.py sdist bdist_wheel
      - name: Run tests
        run: |
          cd src
          python -m pytest addition.py

      - name: Run SonarQube analysis
        run: |
          curl -u $SONARQUBE_TOKEN: $SONARQUBE_URL
          mvn sonar:sonar -Dsonar.host.url=$SONARQUBE_URL -Dsonar.login=$SONARQUBE_TOKEN

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: python-artifact
          path: ./dist/*.tar.gz  # Adjust the path if needed based on your output directory

 
