name: My First GitHub Actions

on: [push]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        python-version: [3.9, 3.8]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      run: |
        cd code
        python -m pytest addition.py

      # Step 4: Package Python code as an artifact
    - name: Create Artifact
      run: |
          mkdir -p artifact
          # Copy all files except the 'artifact' directory
          find . -maxdepth 1 ! -name 'artifact' ! -name '.git' -exec cp -r {} artifact/ \;
          echo "Packaged Python code for artifact publishing."

      # Step 5: Upload the artifact
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
          name: python-code-artifact
          path: artifact
    

  
      


 
